#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

ardana_svc_os_group: "{{ ansible_env['USER'] }}"
ardana_svc_os_user: "{{ ansible_env['USER'] }}"
ardana_user_home: "{{ ansible_env['HOME'] }}"
ardana_openstack_path: "{{ ardana_user_home }}/openstack/"

ardana_svc_component: ardana-service
ardana_svc_service: "{{ ardana_svc_component }}"
ardana_svc_service_venv_name: ardana-service
ardana_svc_cache_dir: "/var/cache/{{ ardana_svc_component }}"
ardana_svc_log_dir: "{% if ARD_SVC is defined -%}
                         /var/log/{{ ardana_svc_component }}
                     {%- else -%}
                         {{ ardana_svc_cache_dir }}
                     {%- endif %}"
ardana_svc_log_file: "{{ ardana_svc_log_dir }}/ardana-service.log"
ardana_svc_process_logs_dir: "{{ ardana_svc_log_dir }}/logs"
ardana_svc_config_dir: "{% if deployer_media_legacy_layout|bool == true -%}
                            {{ ardana_svc_component | config_dir }}
                        {%- else -%}
                            /etc/ardana
                        {%- endif %}"
ardana_svc_config_file: "{{ ardana_svc_config_dir }}/ardana-service.conf"
ardana_svc_port: "{% if ARD_SVC is defined -%}
                      {{ ARD_SVC.advertises.vips.private[0].port }}
                  {%- else -%}
                      9085
                  {%- endif %}"

ardana_svc_internal_service_url:  "{% if ARD_SVC is defined -%}
                                       {{ ARD_SVC.advertises.vips.private[0].url }}
                                   {%- else -%}
                                       http://127.0.0.1:9085
                                   {%- endif %}"
ardana_svc_bind_address: "{% if host is defined -%}
                              {{ host.bind.ARD_SVC.internal.ip_address }}
                          {%- else -%}
                              127.0.0.1
                          {%- endif %}"
ardana_svc_systemd_path: "/etc/systemd/{{ ardana_svc_component }}.service"
ardana_svc_perform_upgrade_check: false
ardana_svc_default_log_level: info
ardana_svc_ignore_stop: false

ui_comp: installer-ui
ui_comp_dir: "{% if deployer_media_legacy_layout|bool -%}
                  {{ ui_comp | venv_dir }}
              {%- else -%}
                  /usr/share/ardana/ardana-installer-ui/web
              {%- endif -%}"

db_file: "{{ ardana_svc_cache_dir }}/db.json"
progress_file: "{{ ardana_svc_cache_dir }}/progress.json"
